### ISSUE TITLE
Secrets are not being injected into pod

### ISSUE THREAD

**Issue by Racer84** [jasonodonnell/vault-agent-demo#4] opened 2021-01-13 18:12 UTC
Hello, 

I tried to walk through demo on my on-premise k8s cluster. Everything went fine until checking secrets in patched static-secrets directory:
```
kubectl exec -ti $( kubectl get pods -n app --field-selector=status.phase==Running -o jsonpath='{.items[0].metadata.name}' ) -n app -c app -- ls /vault/secrets

ls: /vault/secrets: No such file or directory
command terminated with exit code 1
```

There is no container on the pod besides the jodonnellhashi/static-secrets-app:1.0.0:

```
kubectl get pods -n app -o jsonpath="{.items[*].spec.containers[*].image}"
jodonnellhashi/static-secrets-app:1.0.0
```

How to debug this issue?

**Comment by jasonodonnell** [comment] 2021-01-14 17:14
Injection didn't occur then, so something is likely block the mutating webhook. This could be due to firewall rules between your worker and master nodes.

I'd check the injector logs to see if there's errors. If not, its not receiving events from the Kube servers, so its likely a firewall issue. Kube server logs might have more info.

https://www.vaultproject.io/docs/platform/k8s/injector/examples#connectivity

**Comment by Racer84** [comment] 2021-01-15 13:00
Thank you for the tip. Indeed there is a problem while calling webhook. It originates during vault installation. 
When I run script:
```
#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
NAMESPACE='vault'

helm install vault \
  --namespace="${NAMESPACE?}" \
  hashicorp/vault --version=0.7.0
```
kube-apiserver log shows error:
```
W0115 12:42:32.471517       1 dispatcher.go:169] Failed calling webhook, failing open vault.hashicorp.com: failed calling webhook "vault.hashicorp.com": Post https://vault-agent-injector-svc.vault.svc:443/mutate?timeout=30s: Service Unavailable
E0115 12:42:32.471545       1 dispatcher.go:170] failed calling webhook "vault.hashicorp.com": Post https://vault-agent-injector-svc.vault.svc:443/mutate?timeout=30s: Service Unavailable
```
Then injector service is up:
```
$ kubectl get services -n vault
NAME                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
vault                      ClusterIP   10.111.194.152   <none>        8200/TCP,8201/TCP   102s
vault-agent-injector-svc   ClusterIP   10.105.123.55    <none>        443/TCP             102s
vault-internal             ClusterIP   None             <none>        8200/TCP,8201/TCP   102s
```
When I run example from `examples/static-secrets` kube-apiserver log shows the same error.

There is no firewall between my master and worker nodes.

How to debug connectivity to vault injector service?

**Comment by jasonodonnell** [comment] 2021-01-15 14:12
@Racer84 Interesting, I haven't seen this error before. Is the injector running?

`kubectl get pod -n vault`

Are you using istio by any chance?

**Comment by Racer84** [comment] 2021-01-15 14:23
> 
> 
> @Racer84 Interesting, I haven't seen this error before. Is the injector running?
> 
> `kubectl get pod -n vault`
> 

```
$ kubectl get pod -n vault
NAME                                    READY   STATUS    RESTARTS   AGE
vault-0                                 0/1     Pending   0          99s
vault-agent-injector-846f9f7bc6-q8w6j   1/1     Running   0          99s
```

I've just restarted deployment, so the uptime is short.

> Are you using istio by any chance?

I'm not.

**Comment by jasonodonnell** [comment] 2021-01-15 15:18
This is interesting and suggests something went wrong with installation:

```
vault-0                                 0/1     Pending
```

Can you describe that pod? `kubectl describe pod vault-0 -n vault`

What version of K8s is your on premise solution? What version of `kubectl` are you using? Do you have a storage class available?

**Comment by jasonodonnell** [comment] 2021-01-15 15:18
One last thing, can you also describe the injector service?

`kubectl describe service vault-agent-injector-svc -n vault`

**Comment by Racer84** [comment] 2021-01-15 16:16
> This is interesting and suggests something went wrong with installation:
> 
> ```
> vault-0                                 0/1     Pending
> ```
> 
> Can you describe that pod? `kubectl describe pod vault-0 -n vault`
> 

```
Name:           vault-0
Namespace:      vault
Priority:       0
Node:           <none>
Labels:         app.kubernetes.io/instance=vault
                app.kubernetes.io/name=vault
                component=server
                controller-revision-hash=vault-654bf49bb8
                helm.sh/chart=vault-0.7.0
                statefulset.kubernetes.io/pod-name=vault-0
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  StatefulSet/vault
Containers:
  vault:
    Image:       vault:1.5.2
    Ports:       8200/TCP, 8201/TCP, 8202/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP
    Command:
      /bin/sh
      -ec
    Args:
      sed -E "s/HOST_IP/${HOST_IP?}/g" /vault/config/extraconfig-from-values.hcl > /tmp/storageconfig.hcl;
      sed -Ei "s/POD_IP/${POD_IP?}/g" /tmp/storageconfig.hcl;
      /usr/local/bin/docker-entrypoint.sh vault server -config=/tmp/storageconfig.hcl

    Readiness:  http-get https://:8200/v1/sys/health%3Fstandbyok=true&sealedcode=204&uninitcode=204 delay=5s timeout=5s period=3s #success=1 #failure=2
    Environment:
      HOST_IP:               (v1:status.hostIP)
      POD_IP:                (v1:status.podIP)
      VAULT_K8S_POD_NAME:   vault-0 (v1:metadata.name)
      VAULT_K8S_NAMESPACE:  vault (v1:metadata.namespace)
      VAULT_ADDR:           https://127.0.0.1:8200
      VAULT_API_ADDR:       https://$(POD_IP):8200
      SKIP_CHOWN:           true
      SKIP_SETCAP:          true
      HOSTNAME:             vault-0 (v1:metadata.name)
      VAULT_CLUSTER_ADDR:   https://$(HOSTNAME).vault-internal:8201
      HOME:                 /home/vault
    Mounts:
      /home/vault from home (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from vault-token-mjt7s (ro)
      /vault/config from config (rw)
      /vault/data from data (rw)
      /vault/userconfig/demo-vault from userconfig-demo-vault (ro)
      /vault/userconfig/tls-test-client from userconfig-tls-test-client (ro)
      /vault/userconfig/tls-test-server from userconfig-tls-test-server (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-vault-0
    ReadOnly:   false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      vault-config
    Optional:  false
  userconfig-demo-vault:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  demo-vault
    Optional:    false
  userconfig-tls-test-server:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tls-test-server
    Optional:    false
  userconfig-tls-test-client:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tls-test-client
    Optional:    false
  home:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  vault-token-mjt7s:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  vault-token-mjt7s
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  4m22s (x73 over 109m)  default-scheduler  running "VolumeBinding" filter plugin for pod "vault-0": pod has unbound immediate PersistentVolumeClaims
```
> What version of K8s is your on premise solution? What version of `kubectl` are you using? 

```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2020-06-17T11:41:22Z"
  compiler: gc
  gitCommit: c96aede7b5205121079932896c4ad89bb93260af
  gitTreeState: clean
  gitVersion: v1.18.4
  goVersion: go1.13.9
  major: "1"
  minor: "18"
  platform: linux/amd64
serverVersion:
  buildDate: "2020-06-17T11:33:59Z"
  compiler: gc
  gitCommit: c96aede7b5205121079932896c4ad89bb93260af
  gitTreeState: clean
  gitVersion: v1.18.4
  goVersion: go1.13.9
  major: "1"
  minor: "18"
  platform: linux/amd64
```

> Do you have a storage class available?

I don't. This is development setup. Perhaps vault server in examples could/should be run in dev mode too?

> 
> 
> One last thing, can you also describe the injector service?
> 
> `kubectl describe service vault-agent-injector-svc -n vault`

```
Name:              vault-agent-injector-svc
Namespace:         vault
Labels:            app.kubernetes.io/instance=vault
                   app.kubernetes.io/managed-by=Helm
                   app.kubernetes.io/name=vault-agent-injector
Annotations:       meta.helm.sh/release-name: vault
                   meta.helm.sh/release-namespace: vault
Selector:          app.kubernetes.io/instance=vault,app.kubernetes.io/name=vault-agent-injector,component=webhook
Type:              ClusterIP
IP:                10.109.52.64
Port:              <unset>  443/TCP
TargetPort:        8080/TCP
Endpoints:         10.40.0.2:8080
Session Affinity:  None
Events:            <none>
```

**Comment by jasonodonnell** [comment] 2021-01-15 16:40
Everything looks good as far as I can tell, so something seems up with your installation. What CNI are you using on your installation for networking?

Are you able to make this work else where (like a Kind cluster, minikube or GKE)?

As for a good storage class for local development on a bare metal installation, I had a lot of success using this in the past: https://gist.github.com/jasonodonnell/8afce5a648b9f5bdbe7498cbc5e0a8d6.

 I'm not 100% sure this still works but you might find it interesting.

**Comment by Racer84** [comment] 2021-01-15 17:02
> 
> 
> Everything looks good as far as I can tell, so something seems up with your installation. What CNI are you using on your installation for networking?
> 

Weave Net.

> Are you able to make this work else where (like a Kind cluster, minikube or GKE)?
> 

Generally yes, although in this moment it can be difficult.

> As for a good storage class for local development on a bare metal installation, I had a lot of success using this in the past: https://gist.github.com/jasonodonnell/8afce5a648b9f5bdbe7498cbc5e0a8d6.
> 
> I'm not 100% sure this still works but you might find it interesting.

Thank you, I will try it. So there is no way to go through examples without StorageClass?

**Comment by Racer84** [comment] 2021-01-18 16:32
I wonder why the same error message 

```
W0118 16:16:28.455402       1 dispatcher.go:169] Failed calling webhook, failing open vault.hashicorp.com: failed calling webhook "vault.hashicorp.com": Post https://vault-agent-injector-svc.vault.svc:443/mutate?timeout=10s: Service Unavailable
E0118 16:16:28.460098       1 dispatcher.go:170] failed calling webhook "vault.hashicorp.com": Post https://vault-agent-injector-svc.vault.svc:443/mutate?timeout=10s: Service Unavailable
```
appears in the api server log while installing vault in dev mode with:

```
#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
NAMESPACE='vault'

kubectl create namespace "${NAMESPACE}"

helm install vault \
  --namespace="${NAMESPACE?}" \
  hashicorp/vault  --set "server.dev.enabled=true"
```
?

Despite this pods and services of vault are running:

```
$ kubectl get pods
NAME                                   READY   STATUS    RESTARTS   AGE
vault-0                                1/1     Running   0          3m5s
vault-agent-injector-9d6687676-7bn76   1/1     Running   0          3m5s
$ kubectl get services
NAME                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
vault                      ClusterIP   10.106.240.149   <none>        8200/TCP,8201/TCP   3m12s
vault-agent-injector-svc   ClusterIP   10.111.192.181   <none>        443/TCP             3m12s
vault-internal             ClusterIP   None             <none>        8200/TCP,8201/TCP   3m12s
```

**Comment by jasonodonnell** [comment] 2021-03-31 18:29
Unfortunately I'm unsure what's going on in this situation, but closing this issue as this is a personal demo repo where I store my stuff. If you are still experiencing similar issues with the Vault K8s injector, I suggest opening an issue in the Vault K8s repo or on HashiCorp Discuss.

**Closed as completed by jasonodonnell** 2021-03-31 18:29 UTC

**Comment by noorul** [comment] 2022-08-12 16:59
@Racer84 Did you figure out the root cause?
